"""``python -m atp_gateway`` starts the gateway with uvicorn.

``python -m atp_gateway keygen [--write .env]`` generates the required keys.
"""

from __future__ import annotations

import argparse
import contextlib
import logging
import secrets
import sys
from pathlib import Path

import uvicorn

from atp_gateway.app import create_app
from atp_gateway.settings import GatewaySettings


def keygen(argv: list[str]) -> None:
    """Print fresh keys, or write them to a file with ``--write PATH``.

    Writing avoids shell-redirection encoding surprises (Windows PowerShell 5
    writes UTF-16 with ``>``) and refuses to overwrite an existing file.
    """
    parser = argparse.ArgumentParser(prog="atp-gateway keygen")
    parser.add_argument(
        "--write", metavar="PATH", help="write to PATH (e.g. .env); never overwrites"
    )
    args = parser.parse_args(argv)
    lines = [
        "# generated by: python -m atp_gateway keygen  (never commit this file)",
        f"ATP_GRANT_SIGNING_KEY={secrets.token_urlsafe(48)}",
        f"ATP_OPERATOR_KEY={secrets.token_urlsafe(48)}",
    ]
    body = "\n".join(lines) + "\n"
    if args.write is None:
        print(body, end="")
        return
    path = Path(args.write)
    if path.exists():
        sys.exit(f"{path} already exists; refusing to overwrite keys")
    path.write_text(body, encoding="utf-8", newline="\n")
    with contextlib.suppress(OSError):
        path.chmod(0o600)
    print(f"wrote {path} (keys are not shown; open the file to read them)")


def main() -> None:
    if len(sys.argv) > 1 and sys.argv[1] == "keygen":
        keygen(sys.argv[2:])
        return
    parser = argparse.ArgumentParser(prog="atp-gateway")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--log-level", default="info")
    args = parser.parse_args()
    logging.basicConfig(level=args.log_level.upper())
    uvicorn.run(
        create_app(GatewaySettings()), host=args.host, port=args.port, log_level=args.log_level
    )


if __name__ == "__main__":
    main()
