"""The local ATP home: a directory that holds everything ``atp mcp wrap``
needs so that nothing has to be copied, exported or typed.

    .atp/
      atp.db          SQLite: credentials, delegations, grants, traces, ledger
      keys.env        ATP_GRANT_SIGNING_KEY / ATP_OPERATOR_KEY, generated once, mode 600
      policies.yaml   optional declared policy sets (see docs/policies.md)

Location: ``$ATP_HOME`` if set, else ``./.atp``. Offline commands
(``regression add``, ``policy explain``, ``evidence export``) open the same
store directly; no HTTP, no operator key to paste. Treat the directory as
secret: whoever can read ``keys.env`` is the operator.
"""

from __future__ import annotations

import contextlib
import os
import secrets
import stat
from pathlib import Path

from atp_gateway import GatewaySettings, Runtime, build_runtime

KEYS_FILE = "keys.env"
DB_FILE = "atp.db"
POLICY_FILE = "policies.yaml"


class AtpHome:
    def __init__(self, path: str | Path | None = None) -> None:
        raw = path or os.environ.get("ATP_HOME") or ".atp"
        self.path = Path(raw).expanduser().resolve()

    @property
    def db_path(self) -> Path:
        return self.path / DB_FILE

    @property
    def keys_path(self) -> Path:
        return self.path / KEYS_FILE

    @property
    def policy_path(self) -> Path:
        return self.path / POLICY_FILE

    @property
    def exists(self) -> bool:
        return self.db_path.exists()

    def ensure(self) -> AtpHome:
        """Create the directory and keys if missing. Idempotent."""
        self.path.mkdir(parents=True, exist_ok=True)
        if not self.keys_path.exists():
            text = (
                "# generated by atp; whoever reads this file is the operator\n"
                f"ATP_GRANT_SIGNING_KEY={secrets.token_urlsafe(48)}\n"
                f"ATP_OPERATOR_KEY={secrets.token_urlsafe(48)}\n"
            )
            self.keys_path.write_text(text, encoding="utf-8")
            # Windows ignores the mode bits; the directory ACL applies there.
            with contextlib.suppress(OSError):
                os.chmod(self.keys_path, stat.S_IRUSR | stat.S_IWUSR)
        gitignore = self.path / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(
                "# secrets and local state; policies.yaml is meant to be committed\n"
                "keys.env\natp.db\natp.db-*\n",
                encoding="utf-8",
            )
        return self

    def ensure_policy_file(self, version: str, description: str = "") -> bool:
        """Write a starter declared policy set if the home has none. Returns
        True when a file was written."""
        if self.policy_path.exists():
            return False
        text = f"""\
# Declared policy sets for this project (loaded next to the built-in payments sets).
# Every set always includes the kernel policies: delegation valid, capability held,
# resource in scope. Rules add argument-level limits on top. See docs/policies.md.
version: 1
policy_sets:
  - version: {version}
    description: {description or version}
    rules: []
    # examples (uncomment and adapt):
    #  - id: short-notes
    #    applies_to: {{tool: mcp.notes, action: write_note}}
    #    kind: argument_max_length
    #    argument: text
    #    max_length: 2000
    #  - id: never-delete
    #    applies_to: {{tool: mcp.notes, action: delete_note}}
    #    kind: deny
"""
        self.policy_path.write_text(text, encoding="utf-8")
        return True

    def keys(self) -> dict[str, str]:
        out: dict[str, str] = {}
        for line in self.keys_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
        missing = {"ATP_GRANT_SIGNING_KEY", "ATP_OPERATOR_KEY"} - set(out)
        if missing:
            raise RuntimeError(f"{self.keys_path} is missing {sorted(missing)}")
        return out

    def settings(
        self,
        *,
        enforcement_mode: str = "enforce",
        default_policy_set: str | None = None,
    ) -> GatewaySettings:
        keys = self.keys()
        kwargs: dict[str, object] = {
            "database_path": str(self.db_path),
            "grant_signing_key": keys["ATP_GRANT_SIGNING_KEY"],
            "operator_key": keys["ATP_OPERATOR_KEY"],
            "enforcement_mode": enforcement_mode,
            "policy_file": str(self.policy_path) if self.policy_path.exists() else "",
        }
        if default_policy_set:
            kwargs["default_policy_set"] = default_policy_set
        # _env_file=None: the home is authoritative; a stray .env must not override it.
        return GatewaySettings(_env_file=None, **kwargs)  # type: ignore[arg-type]

    def open(self, **kwargs: str) -> Runtime:
        """Open the store for offline commands."""
        if not self.exists:
            raise FileNotFoundError(
                f"no ATP home at {self.path}; run `atp mcp wrap` first or set ATP_HOME"
            )
        return build_runtime(self.settings(**kwargs))
