"""Machine-readable reason codes.

Every decision, error, and blocked execution names exactly one of these. They
are the vocabulary the dashboard, evals, and audit consumers key off, so they
are stable strings rather than free text.
"""

from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    # --- outcomes ---------------------------------------------------------
    ALLOWED = "ALLOWED"
    APPROVAL_REQUIRED_AMOUNT_THRESHOLD = "APPROVAL_REQUIRED_AMOUNT_THRESHOLD"

    # --- authentication --------------------------------------------------
    AGENT_CREDENTIAL_MISSING = "AGENT_CREDENTIAL_MISSING"
    AGENT_CREDENTIAL_INVALID = "AGENT_CREDENTIAL_INVALID"
    AGENT_CREDENTIAL_REVOKED = "AGENT_CREDENTIAL_REVOKED"
    AGENT_CREDENTIAL_EXPIRED = "AGENT_CREDENTIAL_EXPIRED"
    AGENT_IDENTITY_MISMATCH = "AGENT_IDENTITY_MISMATCH"
    CREDENTIAL_SUBJECT_INVALID = "CREDENTIAL_SUBJECT_INVALID"
    OPERATOR_KEY_REQUIRED = "OPERATOR_KEY_REQUIRED"

    # --- delegation / identity -------------------------------------------
    DELEGATION_NOT_FOUND = "DELEGATION_NOT_FOUND"
    DELEGATION_EXPIRED = "DELEGATION_EXPIRED"
    DELEGATION_REVOKED = "DELEGATION_REVOKED"
    DELEGATION_GRANTEE_MISMATCH = "DELEGATION_GRANTEE_MISMATCH"
    DELEGATION_PRINCIPAL_MISMATCH = "DELEGATION_PRINCIPAL_MISMATCH"
    DELEGATION_CHAIN_BROKEN = "DELEGATION_CHAIN_BROKEN"
    DELEGATION_CHAIN_TOO_DEEP = "DELEGATION_CHAIN_TOO_DEEP"
    DELEGATION_ROOT_NOT_HUMAN = "DELEGATION_ROOT_NOT_HUMAN"
    DELEGATION_GRANTOR_NOT_GRANTEE_OF_PARENT = "DELEGATION_GRANTOR_NOT_GRANTEE_OF_PARENT"
    DELEGATION_EXCEEDS_PARENT_CAPABILITIES = "DELEGATION_EXCEEDS_PARENT_CAPABILITIES"
    DELEGATION_EXCEEDS_PARENT_RESOURCE_SCOPE = "DELEGATION_EXCEEDS_PARENT_RESOURCE_SCOPE"
    DELEGATION_EXCEEDS_PARENT_AMOUNT = "DELEGATION_EXCEEDS_PARENT_AMOUNT"
    DELEGATION_EXCEEDS_PARENT_CURRENCIES = "DELEGATION_EXCEEDS_PARENT_CURRENCIES"
    DELEGATION_EXCEEDS_PARENT_EXPIRY = "DELEGATION_EXCEEDS_PARENT_EXPIRY"
    DELEGATION_SELF_GRANT = "DELEGATION_SELF_GRANT"
    DELEGATION_PARENT_INVALID = "DELEGATION_PARENT_INVALID"

    # --- policy ----------------------------------------------------------
    CAPABILITY_NOT_GRANTED = "CAPABILITY_NOT_GRANTED"
    RESOURCE_OUT_OF_SCOPE = "RESOURCE_OUT_OF_SCOPE"
    PAYMENT_EXCEEDS_DELEGATED_AUTHORITY = "PAYMENT_EXCEEDS_DELEGATED_AUTHORITY"
    PAYMENT_CURRENCY_NOT_PERMITTED = "PAYMENT_CURRENCY_NOT_PERMITTED"
    PAYMENT_DESTINATION_NOT_APPROVED = "PAYMENT_DESTINATION_NOT_APPROVED"
    PAYMENT_DESTINATION_RESOURCE_MISMATCH = "PAYMENT_DESTINATION_RESOURCE_MISMATCH"
    PAYMENT_ARGUMENTS_INVALID = "PAYMENT_ARGUMENTS_INVALID"
    TOOL_NOT_REGISTERED = "TOOL_NOT_REGISTERED"
    POLICY_SET_NOT_FOUND = "POLICY_SET_NOT_FOUND"
    POLICY_SET_OVERRIDE_FORBIDDEN = "POLICY_SET_OVERRIDE_FORBIDDEN"

    # --- execution grant -------------------------------------------------
    GRANT_MISSING = "GRANT_MISSING"
    GRANT_MALFORMED = "GRANT_MALFORMED"
    GRANT_SIGNATURE_INVALID = "GRANT_SIGNATURE_INVALID"
    GRANT_EXPIRED = "GRANT_EXPIRED"
    GRANT_ENVELOPE_MISMATCH = "GRANT_ENVELOPE_MISMATCH"
    GRANT_NOT_FOUND = "GRANT_NOT_FOUND"
    GRANT_ALREADY_CONSUMED = "GRANT_ALREADY_CONSUMED"
    GRANT_REVOKED = "GRANT_REVOKED"
    GRANT_DECISION_NOT_ALLOW = "GRANT_DECISION_NOT_ALLOW"
    GRANT_AUDIENCE_MISMATCH = "GRANT_AUDIENCE_MISMATCH"

    # --- execution -------------------------------------------------------
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_NOT_PERMITTED_ON_REPLAY = "EXECUTION_NOT_PERMITTED_ON_REPLAY"
    EVENT_ACTOR_RESERVED = "EVENT_ACTOR_RESERVED"
    EVENT_TYPE_RESERVED = "EVENT_TYPE_RESERVED"

    # --- trace -----------------------------------------------------------
    TRACE_NOT_FOUND = "TRACE_NOT_FOUND"
    TRACE_HAS_NO_PROPOSAL = "TRACE_HAS_NO_PROPOSAL"
